seed: 0
num_epochs: 5

dataset:
  _target_: ddpm.SoundDataset
  directory: .\data
  max_length: 1000
  audio_length: 8000

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 8
  shuffle: true

test:
  run_test: true
  test_split: 0.2
  seed: 1000101

model:
  _target_: ddpm.MLP
  input_dim: 8001
  dim_hidden: 256
  num_hidden_layers: 20

noise_scheduler:
  _target_: ddpm.NoiseScheduler
  beta_start: 1e-5
  beta_end: 1e-2
  num_timesteps: 50

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-5

hydra:
  run:
    dir: "learning_results/${now:%Y-%m-%d_%H-%M-%S}"
