seed: 0
num_epochs: 40

dataset:
  _target_: ddpm.SoundDataset
  directory: .\data
  max_length: 3000
  audio_length: 8000

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 8
  shuffle: true

test:
  run_test: true
  test_split: 0.2
  seed: 1000101

model:
  _target_: ddpm.UNet1D
  in_channels: 1
  base_channels: 128
  num_down: 3

noise_scheduler:
  _target_: ddpm.NoiseScheduler
  beta_start: 1e-6
  beta_end: 1e-3
  num_timesteps: 100

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-5

criterion:
  _target_: ddpm.KLGaussian

hydra:
  run:
    dir: "learning_results/${now:%Y-%m-%d_%H-%M-%S}"
